services:
  node:
    build: .
    container_name: node_server
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "0.0.0.0:3000:3000"  
    restart: unless-stopped
