version: '3.8'
services:
  node:
    image: node:18
    container_name: node_server
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"  
    restart: unless-stopped
